### PR TITLE
Logged error when console can't connect to authentication server

### LINKED ISSUE #1625: [console] No error message is show, when unable to connect to authentication service
When loading the console dashboard.  If it can't reach the authentication service, no error messages are logged.

**To Reproduce**
1. deploy enmasse in minishift (minishift requires you to use routes, instead of cluster ips)'
2. start the console locally with `AUTHENTICATION_SERVICE_HOST=$(oc get service -n $NAMESPACE | awk '/none-authservice/{print $3}')`
3. try to load the console in the browser
4. No errors are in the logs.  Browser says 'no data sent'.
* Also reproducible by having the wrong AUTHENTICATION_SERVICE_HOST.

**Expected behavior**
An error message shows in the log
'agent error Authentication failed! error no: ETIMEDOUT syscall: connect address: 172.30.121.169 port: 5671 code: ETIMEDOUT'

### PR DESCRIPTION
**Pull request by vbusch**
fixes #1625

Signed-off-by: Vanessa <vbusch@redhat.com>

### CODE REVIEW

File: agent/lib/auth_service.js [hunk 1]
```diff
@@ -46,6 +46,7 @@ function authenticate(credentials, options) {
         var handleFailure = function (context) {
             if (!handled) {
                 handled = true;
+            	log.error('Authentication failed! error no: '+ context.error.errno + ' syscall: '+context.error.syscall+ ' address: '+context.error.address+ ' port: '+ context.error.port + ' code: '+ context.error.code);
```
Comment (grs) [inline agent/lib/auth_service.js]: Minor nitpick, looks like indentation is a bit off?

Comment (vbusch) [reply agent/lib/auth_service.js]: fixed my javascript indenting.
