### PR TITLE
Fix label (Address space plan)

### LINKED ISSUE #2778: Global console create address space screen uses wrong label
When creating an address space, you are prompted to choose an "address plan" this should be "address space plan"

Console Create

### PR DESCRIPTION
**Pull request by vbusch**
Fixes #2778

Signed-off-by: Vanessa <vbusch@redhat.com>

### CODE REVIEW

File: console/console-init/ui/src/components/MessagingInstances/MessagingInstance/Enmasse/CreateAddressSpace/Steps/Review.js [hunk 1]
```diff
@@ -37,7 +37,7 @@ class Review extends React.Component {
                 <FormGroup isInline label="Type" fieldId="type">
                   <Text>{newInstance.typeStandard ? 'Standard' : 'Brokered'} Address Plan</Text>
```
Comment (k-wall) [inline console/console-init/ui/src/components/MessagingInstances/MessagingInstance/Enmasse/CreateAddressSpace/Steps/Review.js]: The word "Plan" is wrong.  It should be Space.

**Comment by vbusch** [comment]
> Your changes look good, but I notice a separate typo in the field above. It is so closely related, I feel a separate issue would be overkill.

Thank you.  Corrected it to be 'Standard address space', or 'Brokered address space'.  Also changed it to sentence-style capitalization.

File: console/console-init/ui/src/components/MessagingInstances/MessagingInstance/Enmasse/CreateAddressSpace/Steps/Review.js (hunk 1 above)
Comment (k-wall) [reply console/console-init/ui/src/components/MessagingInstances/MessagingInstance/Enmasse/CreateAddressSpace/Steps/Review.js]: Update looks good, thanks @vbusch
