### PR TITLE
Fix cert bundle certificate provider test

### LINKED ISSUE #2427: WebConsole: incomplete certificate chain
**Describe the bug**
When specifying certificate provider for endpoints in address space the server exposing web console shows an incomplete certificate chain. 
This happens for selfsigned and certBundle cert providers exposing endpoints thorugh openshift passthrough routes.
Given this it's not possible to successfully connect to the web console while trusting the CA that generated the certificate serving SSL in this web page

**To Reproduce**
There are tests in systemtests to reproduce this issue, can be found in this PR #2412 
`make systemtests SYSTEMTEST_ARGS="io.enmasse.systemtest.common.certs.CertProviderTest#testConsole*"`

This can be also reproduced manually creating an address space with selfsigned cert provider in endpoints, like this:
```
apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: myspace
spec:
  type: standard
  plan: standard-unlimited-with-mqtt
  authenticationService:
    type: standard
  endpoints:
    - name: messaging
      service: messaging
      expose:
        type: route
        routeTlsTermination: passthrough
        routeServicePort: amqps
      cert:
        provider: selfsigned
    - name: mqtt
      service: mqtt
      expose:
        type: route
        routeTlsTermination: passthrough
        routeServicePort: secure-mqtt
      cert:
        provider: selfsigned
    - name: console
      service: console
      expose:
        type: route
        routeTlsTermination: passthrough
        routeServicePort: https
      cert:
        provider: selfsigned
```
Given this in a browser the web console certificate looks like this
image

### PR DESCRIPTION
**Pull request by lulf**
* Configure route hosts as well as certificate CN
* Refactor tests to set endpoints and explicitly specify expose
* Limit tests to OpenShift environment as Minikube does not have the capability to do SNI based routing out of the box.
* Reenable tests failing due to http client redirect being followed (#2427)

Fixes #2427

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci run tests profile=isolated testcase=CertProviderTest

File: systemtests/src/test/java/io/enmasse/systemtest/isolated/certs/CertProviderTest.java [hunk 1]
```diff
@@ -4,17 +4,7 @@
  */
 package io.enmasse.systemtest.isolated.certs;
 
-import io.enmasse.address.model.Address;
```
Comment (kornys) [inline systemtests/src/test/java/io/enmasse/systemtest/isolated/certs/CertProviderTest.java]: please stop using `*` import :)

Comment (lulf) [reply systemtests/src/test/java/io/enmasse/systemtest/isolated/certs/CertProviderTest.java]: Gah, i need to setup my ide config again :)

Comment (kornys) [reply systemtests/src/test/java/io/enmasse/systemtest/isolated/certs/CertProviderTest.java]: :D :D yup

**Comment by lulf** [comment]
@enmasse-ci run tests profile=isolated testcase=CertProviderTest

**Comment by lulf** [comment]
@enmasse-ci run tests profile=isolated testcase=CertProviderTest

**Comment by lulf** [comment]
@enmasse-ci run tests profile=isolated testcase=CertProviderTest

**Comment by lulf** [comment]
@enmasse-ci run tests profile=isolated testcase=CertProviderTest
