### PR TITLE
Propagate all headers expected by the kubernetes api

### LINKED ISSUE #2688: Unauthorized error detected in version enmasse-0.28.0-rc3
**Describe the bug**
Cannout create standarrd-address-space in version enmasse-0.28.0-rc3 on k8s
Same step works well in both 0.27.2 & 0.27.0

**To Reproduce**
1. Following the steps in https://enmasse.io/documentation/0.28.0-rc2/kubernetes/
2. Go to step 2.3 "Creating address spaces using the command line"
3. kubectl create -f standard-address-space.yaml
4. See error "error: You must be logged in to the server (error when creating "standard-address-space.yaml": Not authorized)"

### PR DESCRIPTION
**Pull request by lulf**
Read X-Remote-Group and X-Remote-Extra- headers and propagate to subject access review

Fixes #2688

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci run tests profile=smoke

File: api-common/src/main/java/io/enmasse/api/auth/TokenReview.java [hunk 1]
```diff
@@ -4,14 +4,23 @@
...
+    private final List<String> groups;
+    private final Map<String, List<String>> extra;
+
     private final boolean isAuthenticated;
 
-    public TokenReview(String userName, String userId, boolean isAuthenticated) {
+    public TokenReview(String userName, String userId, List<String> groups, Map<String, List<String>> extra, boolean isAuthenticated) {
         this.userName = userName;
         this.userId = userId;
+        this.groups = groups;
```
Comment (k-wall) [inline api-common/src/main/java/io/enmasse/api/auth/TokenReview.java]: Make these immutable copies too, if not null.

File: api-common/src/main/java/io/enmasse/api/auth/KubeAuthApi.java [hunk 2]
```diff
@@ -146,7 +190,29 @@ public TokenReview performTokenReview(String token) {
             resourceAttributes.put("verb", verb);
 
             spec.put("resourceAttributes", resourceAttributes);
-            spec.put("user", user);
+            spec.put("user", tokenReview.getUserName());
+            if (tokenReview.getUserId() != null && !tokenReview.getUserId().isEmpty()) {
```
Comment (k-wall) [inline api-common/src/main/java/io/enmasse/api/auth/KubeAuthApi.java]: Did you mean to guard an empty string username?   I suspect, no, but if yes, then presumably you want to do the same thing for group names and extra names.

File: api-common/src/main/java/io/enmasse/api/auth/KubeAuthApi.java [hunk 3]
```diff
@@ -146,7 +190,29 @@ public TokenReview performTokenReview(String token) {
...
+                spec.put("uid", tokenReview.getUserId());
+            }
+            if (tokenReview.getGroups() != null && !tokenReview.getGroups().isEmpty()) {
```
Comment (k-wall) [inline api-common/src/main/java/io/enmasse/api/auth/KubeAuthApi.java]: Can we extract some utility methods to avoid the duplicated code in this class?

File: api-common/src/main/java/io/enmasse/api/auth/ApiHeaderConfig.java [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+    private final List<String> groupHeaders;
+    private final List<String> extraHeadersPrefix;
+
+    public static ApiHeaderConfig DEFAULT_HEADERS_CONFIG = new ApiHeaderConfig(
+            Collections.singletonList("X-Remote-User"),
+            Collections.singletonList("X-Remote-Group"),
+            Collections.singletonList("X-Remote-Extra-"));
+
+    public ApiHeaderConfig(List<String> userHeaders, List<String> groupHeaders, List<String> extraHeadersPrefix) {
+        this.userHeaders = userHeaders;
```
Comment (k-wall) [inline api-common/src/main/java/io/enmasse/api/auth/ApiHeaderConfig.java]: Make these immutable copies

File: api-common/src/main/java/io/enmasse/api/auth/TokenReview.java [hunk 5]
```diff
@@ -4,14 +4,23 @@
...
 package io.enmasse.api.auth;
 
+import java.util.List;
+import java.util.Map;
+import java.util.Objects;
+
 public class TokenReview {
     private final String userName;
     private final String userId;
+    private final List<String> groups;
```
Comment (k-wall) [inline api-common/src/main/java/io/enmasse/api/auth/TokenReview.java]: Should this be Sets rather than Lists?  You've gone to the trouble to define equality, so I'd expect groups={A,B} and groups={B,A} to be equal.

**Comment by lulf** [comment]
@vbusch @k-wall Please have another look

File: api-common/src/main/java/io/enmasse/api/auth/ApiHeaderConfig.java [hunk 6]
```diff
@@ -18,9 +19,9 @@
             Collections.singletonList("X-Remote-Extra-"));
 
     public ApiHeaderConfig(List<String> userHeaders, List<String> groupHeaders, List<String> extraHeadersPrefix) {
-        this.userHeaders = userHeaders;
-        this.groupHeaders = groupHeaders;
-        this.extraHeadersPrefix = extraHeadersPrefix;
+        this.userHeaders = new ArrayList<>(userHeaders);
```
Comment (k-wall) [inline api-common/src/main/java/io/enmasse/api/auth/ApiHeaderConfig.java]: I prefer immutable object whenever I can as it makes the world an easier place to reason about, so in addition to the change you made, I would wrap the new ArrayList in a Collections.unmodifiable, that way someone calling the getter can't modify my data.
