### PR TITLE
Issue 2328 standard pvc set

### LINKED ISSUE #2328: Broker PVC StorageClass cannot be set
**Describe the bug**
Since v0.25.0 the StorageClass for the broker PVCs should be configurable ([changelog](https://github.com/EnMasseProject/enmasse/blob/master/CHANGELOG.md#0250)).

However, setting the "storageClassName" parameter in the StandardInfraConfig seems to have no effect. The PVCs are still created with the default StorageClass.

**To Reproduce**

1. Modify the `default` StandardInfraConfig to set a StorageClass manually:
```
...
  broker:
    addressFullPolicy: FAIL
    resources:
      memory: 2Gi
      storage: 5Gi
    storageClassName: ontap-volume
...
```

2. Create an AddressSpace 
  ! with a plan (= AddressSpacePlan) that is "defined by" the `default` StandardInfraConfig, such as standard-unlimited
```
apiVersion: enmasse.io/v1beta1
kind: AddressSpace
metadata:
  name: myspace
spec:
  type: standard
  plan: standard-unlimited
```
```
$ oc get addressspaceplan standard-unlimited -o yaml
apiVersion: admin.enmasse.io/v1beta1
kind: AddressSpacePlan
metadata:
  annotations:
    enmasse.io/defined-by: default <--- Defined by the "default" StandardInfraConfig
  name: standard-unlimited
addressSpaceType: standard
addressPlans:
- standard-small-queue
- ...
...
```

3. Create an Address
```
apiVersion: enmasse.io/v1beta1
kind: Address
metadata:
    name: myspace.myqueue
spec:
    address: myqueue
    type: queue
    plan: standard-small-queue
```

4. Review the StorageClass of the newly created PVC (can take a minute to appear)
```
$ oc get pvc
NAME                            STATUS    VOLUME                                       CAPACITY     ACCESS MODES   STORAGECLASS   AGE
data-broker-a10yprjqii-mvcn-0   Pending                                                                            **ontap-qtree**    3s
```
NOTE: **ontap-qtree** is our default SC, not the SC as defined in the StandardInfraConfig above (**ontap-volume**)

We also tried to create our own StandardInfraConfig, AddressSpacePlan and AddressPlan resources, to not overwrite the preinstalled `default` StandardInfraConfig. The results are the same.

**Expected behavior**
The PVC should have the StorageClass as configured in the {Standard,Brokered}InfraConfig.

### PR DESCRIPTION
**Pull request by lulf**
Fixes #2328

### CODE REVIEW

File: standard-controller/src/main/java/io/enmasse/controller/standard/TemplateBrokerSetGenerator.java [hunk 1]
```diff
@@ -110,6 +110,11 @@ private KubernetesList processTemplate(String clusterId, int numReplicas, Addres
             if (item instanceof StatefulSet) {
                 StatefulSet set = (StatefulSet) item;
                 set.getSpec().setReplicas(numReplicas);
+                if (standardInfraConfig.getSpec().getBroker().getStorageClassName() != null) {
```
Comment (k-wall) [inline standard-controller/src/main/java/io/enmasse/controller/standard/TemplateBrokerSetGenerator.java]: The Broker object within the StandardInfraConfig could be absent, so a null check is required for `standardInfraConfig.getSpec().getBroker()`
