### PR TITLE
Compare addresses by their name

### LINKED ISSUE #4317: Addresses with different casing are not becoming ready
**Describe the bug**
When addresses with mixed casing are created, and this ends up with different ordering of metadata.name and spec.address, addresses may be wrongly marked as not ready. 

In standard address space, this is automatically resolved due to the standard-controller replacing the addresses, whereas in the brokered address space, the agent will not update the readiness of addresses.

**To Reproduce**
1. Create address with name 'ab' and address 'AB'.
2. Create address with name 'aa' and address 'aa'.
3. Observe that the address with name 'ab' ends up in the not ready state

**Expected behavior**
Address should be ready.

### PR DESCRIPTION
**Pull request by lulf**
### Type of change

- Bugfix

### Description

Comparing addresses using their address can cause the expected
ordered input to changes function to be broken, as the addresses
retrieved from kubernetes are sorted by their name.

Fixes #4317

### Checklist

- [ ] Update/write design documentation in `./documentation/design`
- [x] Write tests and make sure they pass
- [ ] Update documentation
- [ ] Check RBAC rights for Kubernetes / OpenShift roles
- [x] Try your changes from Pod inside your Kubernetes and OpenShift cluster, not just locally
- [x] Reference relevant issue(s) and close them after merging
- [x] Update CHANGELOG.md

### CODE REVIEW

**Comment by lulf** [comment]
@enmasse-ci run tests profile=shared

File: systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/QueueTest.java [hunk 1]
```diff
@@ -58,6 +60,41 @@ void tearDown() throws Exception {
         }
     }
 
+
+    // Test reproducing #4317
+    @Test
+    @Tag(NON_PR)
+    void testAddressOrderingIssue4317() throws Exception {
```
Comment (kornys) [inline systemtests/src/test/java/io/enmasse/systemtest/shared/brokered/QueueTest.java:67]: @lulf please do not name test with issue number :)

**Comment by lulf** [comment]
@enmasse-ci run tests profile=isolated

**Comment by lulf** [comment]
I’ve verified that failing shared tests pass locally, so they are likely not related to this change
